### ISSUE TITLE
Generated Architecture Visualization for your Project

### ISSUE THREAD

**Issue by johspaeth** [PRX/Porter#121]
Hi @farski 

I am currently working on automated generated architecture diagrams for Serverless and CloudFormation projects. Your project is particularly interesting as it represents a good real-world use case. 

The tool I am working on generated [the following diagram](https://dashboard.codeshield.io/public/result/9c7fbc04-1cbd-46f9-8255-8266d393ceca?utm_source=github&utm_medium=shared&utm_campaign=issue). I am happy to get your feedback. 

Does the diagram match the architecture you have in mind? Seems like `TranscriptionJobStartLambdaFunction` and `IngestLambdaFunction` are the only two Lambdas which write to the Bucket, however all Lambdas have read access on `ArtifactBucket`, is that on purpose?

**Comment by farski** [comment]
I don't think that link goes to the correct diagram

**Comment by johspaeth** [comment]
My apologies. I fixed the link.

**Comment by farski** [comment]
I didn't follow every line on that graph, but those two Lambdas do make sense as the only two that write to that bucket. Most other Lambdas, but not all, should have read access.
