### ISSUE TITLE
Add user agent to Ingest

### ISSUE THREAD

**Issue by farski** [PRX/Porter#47]

**Comment by farski** [comment]
@cavis Let me know if you have any thoughts on this one

**Comment by cavis** [comment]
I'd opt for something simple, that includes "Bot" so it's obvious.  And some sort of version number.  It's also more common to use camelcase, and keep the name 1-word no spaces.  (If you need a delimiter in the app-name piece, dashes are the most common).

```
PrxPorterBot/0.0.1
PRXPorterDownloaderBot/0.0.1
PrxBotPorter/0.0.1
```

Something like that.
